"""add_proctoring_fields

Revision ID: e0437ee09b20
Revises: f1c9c7b8d4e5
Create Date: 2026-08-12 14:01:18.178286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0437ee09b20'
down_revision: Union[str, None] = 'f1c9c7b8d4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_sessions', sa.Column('security_mode', sa.String(), nullable=False, server_default='standard'))
    op.add_column('interview_sessions', sa.Column('proctoring_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_sessions', 'proctoring_metadata')
    op.drop_column('interview_sessions', 'security_mode')
    # ### end Alembic commands ###
